<a href="https://colab.research.google.com/github/efraimar/pytorch_study/blob/main/Autograd_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [6]:

x = torch.tensor([1.],requires_grad=True)
v = 4 * x
z = v - 1
w = z ** 2
print(x)
print(v)
print(z)
print(w)

tensor([1.], requires_grad=True)
tensor([4.], grad_fn=<MulBackward0>)
tensor([3.], grad_fn=<SubBackward0>)
tensor([9.], grad_fn=<PowBackward0>)


In [10]:
x = torch.tensor([1.],requires_grad=True)
l = (4*x-1)**2
print(l)
l.backward()
print(x.grad)

tensor([9.], grad_fn=<PowBackward0>)
tensor([24.])


In [3]:
x = torch.tensor([1.],requires_grad = True)
z = torch.tensor([4.],requires_grad = True)
w = torch.tensor([1.])
loss = (z * x - w)**2
print(f"loss:{loss} ")
loss.backward()
print(f"loss x=1: \n{x.grad}\n")
print(f"loss z=4:\n{z.grad}")


loss:tensor([9.], grad_fn=<PowBackward0>) 
loss x=1: 
tensor([24.])

loss z=4:
tensor([6.])




1.requires_grad()=True מבצע חישוב גרדיאנט אוטומטי עבור כל פונקציה המכילה  backward


2.   

